# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.process_execution_service import service_pb2 as proto_dot_process__execution__service_dot_service__pb2


class ProcessExecutionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTreatmentsByPatientID = channel.unary_unary(
                '/alt_team.process_execution_service.ProcessExecutionService/GetTreatmentsByPatientID',
                request_serializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDRequest.SerializeToString,
                response_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDResponse.FromString,
                )
        self.GetTreatmentByID = channel.unary_unary(
                '/alt_team.process_execution_service.ProcessExecutionService/GetTreatmentByID',
                request_serializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDRequest.SerializeToString,
                response_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDResponse.FromString,
                )
        self.GetPatientsByDoctorID = channel.unary_unary(
                '/alt_team.process_execution_service.ProcessExecutionService/GetPatientsByDoctorID',
                request_serializer=proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDRequest.SerializeToString,
                response_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDResponse.FromString,
                )
        self.CompleteTasks = channel.unary_unary(
                '/alt_team.process_execution_service.ProcessExecutionService/CompleteTasks',
                request_serializer=proto_dot_process__execution__service_dot_service__pb2.CompleteTasksRequest.SerializeToString,
                response_deserializer=proto_dot_process__execution__service_dot_service__pb2.CompleteTasksResponse.FromString,
                )


class ProcessExecutionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTreatmentsByPatientID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTreatmentByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientsByDoctorID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTreatmentsByPatientID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTreatmentsByPatientID,
                    request_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDRequest.FromString,
                    response_serializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDResponse.SerializeToString,
            ),
            'GetTreatmentByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTreatmentByID,
                    request_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDRequest.FromString,
                    response_serializer=proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDResponse.SerializeToString,
            ),
            'GetPatientsByDoctorID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientsByDoctorID,
                    request_deserializer=proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDRequest.FromString,
                    response_serializer=proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDResponse.SerializeToString,
            ),
            'CompleteTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTasks,
                    request_deserializer=proto_dot_process__execution__service_dot_service__pb2.CompleteTasksRequest.FromString,
                    response_serializer=proto_dot_process__execution__service_dot_service__pb2.CompleteTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alt_team.process_execution_service.ProcessExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessExecutionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTreatmentsByPatientID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.process_execution_service.ProcessExecutionService/GetTreatmentsByPatientID',
            proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDRequest.SerializeToString,
            proto_dot_process__execution__service_dot_service__pb2.GetTreatmentsByPatientIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTreatmentByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.process_execution_service.ProcessExecutionService/GetTreatmentByID',
            proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDRequest.SerializeToString,
            proto_dot_process__execution__service_dot_service__pb2.GetTreatmentByIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPatientsByDoctorID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.process_execution_service.ProcessExecutionService/GetPatientsByDoctorID',
            proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDRequest.SerializeToString,
            proto_dot_process__execution__service_dot_service__pb2.GetPatientsByDoctorIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.process_execution_service.ProcessExecutionService/CompleteTasks',
            proto_dot_process__execution__service_dot_service__pb2.CompleteTasksRequest.SerializeToString,
            proto_dot_process__execution__service_dot_service__pb2.CompleteTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
