# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.schema_service import schema_service_pb2 as proto_dot_schema__service_dot_schema__service__pb2


class SchemaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchema = channel.unary_unary(
                '/alt_team.schema_service.SchemaService/CreateSchema',
                request_serializer=proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaResponse.FromString,
                )
        self.GetSchemaByID = channel.unary_unary(
                '/alt_team.schema_service.SchemaService/GetSchemaByID',
                request_serializer=proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDRequest.SerializeToString,
                response_deserializer=proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDResponse.FromString,
                )
        self.DeleteSchemaByID = channel.unary_unary(
                '/alt_team.schema_service.SchemaService/DeleteSchemaByID',
                request_serializer=proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDRequest.SerializeToString,
                response_deserializer=proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDResponse.FromString,
                )


class SchemaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemaByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchemaByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchema,
                    request_deserializer=proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaRequest.FromString,
                    response_serializer=proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaResponse.SerializeToString,
            ),
            'GetSchemaByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemaByID,
                    request_deserializer=proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDRequest.FromString,
                    response_serializer=proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDResponse.SerializeToString,
            ),
            'DeleteSchemaByID': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchemaByID,
                    request_deserializer=proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDRequest.FromString,
                    response_serializer=proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alt_team.schema_service.SchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchemaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.schema_service.SchemaService/CreateSchema',
            proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaRequest.SerializeToString,
            proto_dot_schema__service_dot_schema__service__pb2.CreateSchemaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSchemaByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.schema_service.SchemaService/GetSchemaByID',
            proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDRequest.SerializeToString,
            proto_dot_schema__service_dot_schema__service__pb2.GetSchemaByIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSchemaByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alt_team.schema_service.SchemaService/DeleteSchemaByID',
            proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDRequest.SerializeToString,
            proto_dot_schema__service_dot_schema__service__pb2.DeleteSchemaByIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
